apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cattle.io/status: >-
      {"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2025-10-14T06:07:40Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2025-10-14T06:07:40Z"}]}
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"monitoring"}}
    lifecycle.cattle.io/create.namespace-auth: 'true'
  creationTimestamp: '2025-10-14T06:07:39Z'
  finalizers:
    - controller.cattle.io/namespace-auth
  labels:
    kubernetes.io/metadata.name: monitoring
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:kubernetes.io/metadata.name: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2025-10-14T06:07:39Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:cattle.io/status: {}
            f:lifecycle.cattle.io/create.namespace-auth: {}
          f:finalizers:
            .: {}
            v:"controller.cattle.io/namespace-auth": {}
      manager: rancher
      operation: Update
      time: '2025-10-14T06:07:39Z'
  name: monitoring
  resourceVersion: '10572'
  uid: 923335fe-839b-4d82-9f21-00d42831f5eb
spec:
  finalizers:
    - kubernetes
status:
  phase: Active